# Generated by Django 3.0.2 on 2020-02-01 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('height', models.FloatField()),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_place', models.CharField(max_length=40, null=True)),
                ('picture_url', models.ImageField(default='default-picture.png', upload_to='media')),
                ('trainer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Trainer')),
            ],
        ),
    ]
