# Generated by Django 3.0.2 on 2020-02-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20200202_0045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='trainer_id',
            new_name='trainer',
        ),
    ]
