# Generated by Django 3.0.2 on 2020-02-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0004_auto_20200201_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(),
            preserve_default=False,
        ),
    ]
