# Generated by Django 3.0.2 on 2020-02-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_athlete_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='birth_place',
            field=models.CharField(choices=[('001', 'Bogotá'), ('002', 'Pasto'), ('003', 'Tunja'), ('004', 'Barranquilla'), ('005', 'Medellín'), ('007', 'Cartagena'), ('008', 'Manizales'), ('009', 'Yopal')], default='', max_length=3),
        ),
    ]
