# Generated by Django 3.0.2 on 2020-02-02 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='participation_id',
            new_name='participation',
        ),
    ]
