# Generated by Django 3.0.3 on 2020-02-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0003_auto_20200202_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
