# Generated by Django 3.0.3 on 2020-02-24 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0004_auto_20200222_2349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-datetime']},
        ),
    ]
