# Generated by Django 3.0.3 on 2020-02-24 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participations', '0005_auto_20200224_0514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['datetime']},
        ),
    ]
